runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
# - url: /static
#   static_dir: static
- url: /js
  static_dir: js
- url: /css
  static_dir: /static/css
- url: /.*
  script: main.app
# [END handlers]

libraries:
- name: MySQLdb
  version: "1.2.5"
